### ISSUE TITLE
TAF-Demo is not able to clone

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry-holding/edgex-taf#2]
I tried to clone the demo code which described in the README, it seems need to provide the username and password.

```
$ git clone --recurse-submodules https://github.impcloud.net/IVS/TAF-Demo.git
Cloning into 'TAF-Demo'...
Username for 'https://github.impcloud.net': 
```

@ramya-ranganathan Could you help check the TAF-Demo repository?

**Comment by jlopezgu** [comment]
Sorry that was the reference to the original repo, will create a PR to update it.

**Comment by juan-pablo-lopez-gutierrez** [comment]
I created a PR with the fix for this issue.

**Comment by jamesrgregg** [comment]
Why are you cloning into GitHub.impcloud.net?

**Comment by juan-pablo-lopez-gutierrez** [comment]
The README was done when we had the repo in github.impcloud.net. I created a PR with the updated command: 
git clone --recurse-submodules https://github.com/edgexfoundry-holding/edgex-taf.git

**Comment by weichou1229** [comment]
Fixed by https://github.com/edgexfoundry-holding/edgex-taf/pull/4
